airport:
  - id: 1
    description: John_F._Kennedy_International_Airport
    city: New_York
    country: USA
    iata_code: JFK
    latitude: 40.6413
    longitude: -73.7781

  - id: 2
    description: Los_Angeles_International_Airport
    city: Los_Angeles
    country: USA
    iata_code: LAX
    latitude: 33.9416
    longitude: -118.4085

  - id: 3
    description: O'Hare_International_Airport
    city: Chicago
    country: USA
    iata_code: ORD
    latitude: 41.9742
    longitude: -87.9073

  - id: 4
    description: Fictional1_Airport_A
    city: FictionCity_A
    country: FictionLand
    iata_code: FCA
    latitude: 50.1234
    longitude: 60.5678

  - id: 5
    description: Fictional2_Airport_B
    city: FictionCity_B
    country: FictionLand
    iata_code: FCB
    latitude: 52.2345
    longitude: 62.6789

  - id: 6
    description: Fictional3_Airport_C
    city: FictionCity_C
    country: FictionLand
    iata_code: FCC
    latitude: 54.3456
    longitude: 64.7890

  - id: 7
    description: Fictional4_Airport_D
    city: FictionCity_D
    country: FictionLand
    iata_code: FCD
    latitude: 56.4567
    longitude: 66.8901

  - id: 8
    description: Fictional5_Airport_E
    city: FictionCity_E
    country: FictionLand
    iata_code: FCE
    latitude: 58.5678
    longitude: 68.9012

  - id: 9
    description: Fictional6_Airport_F
    city: FictionCity_F
    country: FictionLand
    iata_code: FCF
    latitude: 60.6789
    longitude: 70.0123

  - id: 10
    description: Fictional7_Airport_G
    city: FictionCity_G
    country: FictionLand
    iata_code: FCG
    latitude: 62.7890
    longitude: 72.1234

    id: 11
    description: Hartsfield-Jackson_Atlanta_International_Airport
    city: Atlanta
    country: USA
    iata_code: ATL
    latitude: 33.6407
    longitude: -84.4277

Sample 2:

    id: 12
    description: Heathrow_Airport
    city: London
    country: UK
    iata_code: LHR
    latitude: 51.4700
    longitude: -0.4543

Sample 3:

    id: 13
    description: Charles_de_Gaulle_Airport
    city: Paris
    country: France
    iata_code: CDG
    latitude: 49.0097
    longitude: 2.5479

Sample 4:

    id: 14
    description: Tokyo_Haneda_Airport
    city: Tokyo
    country: Japan
    iata_code: HND
    latitude: 35.5489
    longitude: 139.7840

Sample 5:

    id: 15
    description: Sydney_Kingsford_Smith_Airport
    city: Sydney
    country: Australia
    iata_code: SYD
    latitude: -33.9399
    longitude: 151.1753

Sample 6:

    id: 16
    description: Frankfurt_Airport
    city: Frankfurt
    country: Germany
    iata_code: FRA
    latitude: 50.0344
    longitude: 8.5627

Sample 7:

    id: 17
    description: Dubai_International_Airport
    city: Dubai
    country: UAE
    iata_code: DXB
    latitude: 25.2532
    longitude: 55.3657

Sample 8:

    id: 18
    description: Beijing_Capital_International_Airport
    city: Beijing
    country: China
    iata_code: PEK
    latitude: 40.0801
    longitude: 116.5848

Sample 9:

    id: 19
    description: Toronto_Pearson_International_Airport
    city: Toronto
    country: Canada
    iata_code: YYZ
    latitude: 43.6777
    longitude: -79.6248

    id: 20
    description: Dubai_Al_Maktoum_International_Airport
    city: Dubai
    country: UAE
    iata_code: DWC
    latitude: 24.8978
    longitude: 55.1616

    id: 21
    description: Munich_Airport
    city: Munich
    country: Germany
    iata_code: MUC
    latitude: 48.3537
    longitude: 11.7861

    id: 22
    description: Hong_Kong_International_Airport
    city: Hong Kong
    country: China
    iata_code: HKG
    latitude: 22.3080
    longitude: 113.9185

    id: 23
    description: Rome_Leonardo_da_Vinci_Fiumicino_Airport
    city: Rome
    country: Italy
    iata_code: FCO
    latitude: 41.8003
    longitude: 12.2388

    id: 24
    description: Istanbul_Airport
    city: Istanbul
    country: Turkey
    iata_code: IST
    latitude: 41.2755
    longitude: 28.7510

    id: 25
    description: Amsterdam_Schiphol_Airport
    city: Amsterdam
    country: Netherlands
    iata_code: AMS
    latitude: 52.3081
    longitude: 4.7642

    id: 26
    description: Singapore_Changi_Airport
    city: Singapore
    country: Singapore
    iata_code: SIN
    latitude: 1.3644
    longitude: 103.9915

    id: 27
    description: Incheon_International_Airport
    city: Incheon
    country: South Korea
    iata_code: ICN
    latitude: 37.4694
    longitude: 126.4509

    id: 28
    description: São_Paulo–Guarulhos_International_Airport
    city: São Paulo
    country: Brazil
    iata_code: GRU
    latitude: -23.4346
    longitude: -46.4693

    id: 29
    description: Mexico_City_International_Airport
    city: Mexico City
    country: Mexico
    iata_code: MEX
    latitude: 19.4361
    longitude: -99.0719

    id: 30
    description: Dubai_World_Central_Airport
    city: Dubai
    country: UAE
    iata_code: DWC
    latitude: 24.9009
    longitude: 55.1631