airports:
  - id: 1
    name: John F. Kennedy International Airport
    city: New York
    country: USA
    iata_code: JFK
    coordinates:
      lat: 40.6413
      lon: -73.7781

  - id: 2
    name: Los Angeles International Airport
    city: Los Angeles
    country: USA
    iata_code: LAX
    coordinates:
      lat: 33.9416
      lon: -118.4085

  - id: 3
    name: O'Hare International Airport
    city: Chicago
    country: USA
    iata_code: ORD
    coordinates:
      lat: 41.9742
      lon: -87.9073

flights:
  - origin: JFK
    destination: LAX
    airline: Delta Airlines
    flight_no: DL402
    duration: 6h

  - origin: LAX
    destination: ORD
    airline: United Airlines
    flight_no: UA110
    duration: 4h


