FROM python:alpine3.18 AS build

WORKDIR /app

COPY requirements.fastapi.txt requirements.fastapi.txt
COPY main.py .

RUN pip wheel --no-cache-dir --wheel-dir /app/wheels install -r requirements.fastapi.txt

FROM python:alpine3.18

WORKDIR /app

COPY --from=build /app/wheels /app/wheels
COPY --from=build /app/main.py /app/main.py

RUN pip install --no-cache /app/wheels/* && \
    touch __init__.py

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]