FROM python:alpine3.18

WORKDIR /app

COPY requirements.fastapi.txt requirements.fastapi.txt
COPY main.py .

RUN pip --no-cache-dir install -r requirements.fastapi.txt && \
    touch __init__.py

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]